apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/monswiklund/todo-k8s.git
    targetRevision: main
    path: charts/todo
    helm:
      valueFiles:
        - values-eks-ghcr.yaml
      parameters:
        - name: image.tag
          value: eks-20251018v3
  destination:
    server: https://kubernetes.default.svc
    namespace: todo-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
