# Argo CD Application som synkar Todo-appen från Git till EKS
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/monswiklund/todo-k8s.git
    targetRevision: main
    path: charts/todo 
  destination:
    server: https://kubernetes.default.svc
    namespace: todo-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
