global:
  namespace: todo-app

image:
  repository: ghcr.io/monswiklund/todo-app
  tag: 9ddd6eb4bb965flatest

webapp:
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
  env:
    mongoUri: ""

mongodb:
  storage:
    storageClass: ebs-sc
  auth:
    rootPassword: changeme
    appPassword: changeme

storageClass:
  enabled: true
  name: ebs-sc
  provisioner: ebs.csi.eks.amazonaws.com
  parameters:
    type: gp3
    encrypted: "true"
