# Default configuration values for the Todo Helm chart
replicaCount: 3

image:
  repository: ghcr.io/monswiklund/todo-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: nginx
  host: todo.localhar
  annotations: {}
  tls: []

env:
  ASPNETCORE_ENVIRONMENT: Production
  ASPNETCORE_URLS: http://+:8080
  secret:
    name: mongo-credentials
    key: MONGO_URI

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
