namespace: todo-app

nameOverride: ""
fullnameOverride: ""

image:
  repository: ghcr.io/monswiklund/todo-app
  tag: latest
  pullPolicy: IfNotPresent

mongodb:
  enabled: true
  image: mongo:6.0
  replicas: 1
  database: ToDoAppDb
  storage:
    enabled: true
    size: 5Gi
    storageClass: ""
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

webapp:
  enabled: true
  replicas: 2
  port: 8080
  service:
    type: ClusterIP
    port: 80
    annotations: {}
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi

mongoExpress:
  enabled: false
  image: mongo-express:1.0.2
  replicas: 1
  port: 8081
  service:
    type: ClusterIP
    port: 8081
    annotations: {}
  auth:
    username: admin
    password: pass
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi

initJob:
  enabled: true
  backoffLimit: 3
  delaySeconds: 10
  todos:
    - id: 1
      name: "Learn Kubernetes"
      isComplete: false
    - id: 2
      name: "Deploy MongoDB"
      isComplete: true

storageClass:
  enabled: false
  name: ebs-sc
  provisioner: ebs.csi.eks.amazonaws.com
  volumeBindingMode: WaitForFirstConsumer
  parameters:
    type: gp3
    encrypted: "true"
