image:
  repository: ghcr.io/monswiklund/todo-app
  tag: fdf1e51

mongodb:
  storage:
    storageClass: ebs-sc

webapp:
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing

mongoExpress:
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing

storageClass:
  enabled: true
