namespace: todo-app

nameOverride: ""
fullnameOverride: ""

image:
  repository: ghcr.io/monswiklund/todo-app
  tag: latest
  pullPolicy: IfNotPresent

mongodb:
  enabled: true
  image: mongo:6.0
  replicas: 1
  database: ToDoAppDb
  storage:
    enabled: true
    size: 5Gi
    storageClass: ""
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

webapp:
  enabled: true
  replicas: 2
  port: 8080
  service:
    type: ClusterIP
    port: 80
    annotations: {}
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi

initJob:
  enabled: true
  backoffLimit: 3
  delaySeconds: 10
  todos:
    - Title: "Learn Kubernetes"
      Description: "Gå igenom Helm-workshopen och dokumentera lärdomar"
      IsCompleted: false
    - Title: "Deploy MongoDB"
      Description: "Provisionera lagring och verifiera anslutningar"
      IsCompleted: true
