# Secret storing MongoDB credentials and connection string
apiVersion: v1
kind: Secret
metadata:
  name: mongo-credentials
  namespace: todo-app
type: Opaque
stringData:
  MONGO_USER: "<mongo-user>"
  MONGO_PASSWORD: "<mongo-password>"
  MONGO_URI: "mongodb+srv://<mongo-user>:<mongo-password>@cluster0.example.mongodb.net/todo-app?retryWrites=true&w=majority"
