apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data
  namespace: todo-app
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath   # byt från 'standard' till 'hostpath'