# Secret storing MongoDB credentials and connection string
apiVersion: v1
kind: Secret
metadata:
  name: mongo-credentials
  namespace: todo-app
type: Opaque
stringData:
  MONGO_USER: monswiklund99_db_user
  MONGO_PASSWORD: u3VTHaxMUKrshr0x
  MONGO_URI: mongodb+srv://monswiklund99_db_user:u3VTHaxMUKrshr0x@cluster0.ldy3bdu.mongodb.net/todo-app?retryWrites=true&w=majority&appName=Cluster0
