{{- if .Values.mongoExpress.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
    app: mongo-express
  {{- with .Values.mongoExpress.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.mongoExpress.service.type }}
  selector:
    app: mongo-express
  ports:
    - port: {{ .Values.mongoExpress.service.port }}
      targetPort: {{ .Values.mongoExpress.port }}
      protocol: TCP
{{- end }}
