{{- if .Values.mongo.auth.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongo.auth.secretName }}
  namespace: {{ include "todo.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "todo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: mongo
type: Opaque
stringData:
  MONGO_USER: "{{ default "" .Values.mongo.auth.username }}"
  MONGO_PASSWORD: "{{ default "" .Values.mongo.auth.password }}"
  MONGO_URI: "{{ default "" .Values.mongo.auth.uri }}"
{{- end }}
