{{- if .Values.mongoExpress.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
    app: mongo-express
spec:
  replicas: {{ .Values.mongoExpress.replicas }}
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: {{ .Values.mongoExpress.image }}
          ports:
            - containerPort: {{ .Values.mongoExpress.port }}
              name: http
          env:
            - name: ME_CONFIG_MONGODB_URL
              value: "mongodb://mongodb-service:27017"
            - name: ME_CONFIG_BASICAUTH_USERNAME
              value: {{ .Values.mongoExpress.auth.username | quote }}
            - name: ME_CONFIG_BASICAUTH_PASSWORD
              value: {{ .Values.mongoExpress.auth.password | quote }}
          resources:
            {{- toYaml .Values.mongoExpress.resources | nindent 12 }}
{{- end }}
