{{- if and .Values.mongodb.enabled .Values.initJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "todo-app.fullname" . }}-mongodb-init
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
    app: mongodb-init
spec:
  backoffLimit: {{ .Values.initJob.backoffLimit }}
  template:
    metadata:
      labels:
        app: mongodb-init
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mongo-init
          image: {{ .Values.mongodb.image }}
          command:
            - /bin/bash
            - -c
            - |
              sleep {{ .Values.initJob.delaySeconds }}
              mongosh mongodb-service:27017/{{ .Values.mongodb.database }} --quiet <<'EOF'
              const todos = {{ toJson .Values.initJob.todos }};
              const existing = db.TodoItems.find().count();
              if (existing === 0) {
                db.TodoItems.insertMany(todos);
              }
              EOF
{{- end }}
