apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todo.componentName" (list . "app") }}
  namespace: {{ include "todo.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "todo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.todoApp.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "todo.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "todo.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: api
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: todo-app
          image: "{{ .Values.todoApp.image.repository }}:{{ .Values.todoApp.image.tag }}"
          imagePullPolicy: {{ .Values.todoApp.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.todoApp.service.targetPort }}
              name: http
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "{{ .Values.todoApp.env.aspnetCoreEnvironment }}"
            - name: ASPNETCORE_URLS
              value: "{{ .Values.todoApp.env.aspnetCoreUrls }}"
            - name: MONGO_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongo.auth.secretName }}
                  key: MONGO_URI
          {{- with .Values.todoApp.readinessProbe }}
          readinessProbe:
            httpGet:
              path: {{ .path }}
              port: http
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
          {{- end }}
          {{- with .Values.todoApp.livenessProbe }}
          livenessProbe:
            httpGet:
              path: {{ .path }}
              port: http
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
          {{- end }}
          {{- with .Values.todoApp.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.todoApp.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.todoApp.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.todoApp.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
