{{- if .Values.webapp.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:{{ .Values.webapp.port }}"
  MONGO_CONNECTION_STRING: "mongodb://mongodb-service:27017/{{ .Values.mongodb.database }}"
  MONGO_URI: "mongodb://mongodb-service:27017/{{ .Values.mongodb.database }}"
{{- end }}
