apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app.componentName" (list . "webapp") }}
  namespace: {{ include "todo-app.namespace" . }}
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: webapp
  {{- with .Values.webapp.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.webapp.service.type }}
  selector:
    {{- include "todo-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: webapp
  ports:
    - name: http
      port: {{ .Values.webapp.service.port }}
      targetPort: {{ .Values.webapp.service.targetPort }}
